<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class StoreBlogPost extends FormRequest
{

    protected $redirect='get-old-value';
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
//        return false;
        return  true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */

    public function rules()
    {

        return [

//'name'=>'required'
            //
        ];
    }

public function withValidator($validator){

     // var_dump($validator);
}

public function attributes()
{
//    return parent::attributes(); // TODO: Change the autogenerated stub

    return ['name'=>'name string'];
}

public function messages()
{
//    return parent::messages(); // TODO: Change the autogenerated stub

    return [
     'name.required'=>':attribute is required!'
    ];
}


}
