<?php

namespace App\Providers;
use Tst\Classes\ClassA;
use Illuminate\Support\ServiceProvider;
use Illuminate\Contracts\Support\DeferrableProvider;
use Illuminate\Foundation\Application;
class DeferProvider extends ServiceProvider implements DeferrableProvider
{
    /**
     * Register services.
     *
     * @return void
     */
    public function register()
    {
        //
        $this->app->singleton(ClassA::class,function($app){

            return new ClassA([1,2,3]) ;
        });
    }

    /**
     * Bootstrap services.
     *
     * @return void
     */
    public function boot()
    {
        //
    }

    function provides()
    {
      //  return parent::provides(); // TODO: Change the autogenerated stub
        return [ClassA::class];

    }
}
